version: '3.4'

services:
  grpcsample:
    image: ${DOCKER_REGISTRY-}grpcsample
    build:
      context: .
      dockerfile: GrpcSample/Dockerfile
  grpcclient:
    image: ${DOCKER_REGISTRY-}grpcclient
    build:
      context: .
      dockerfile: GrpcClient/Dockerfile
